# ignore:
#   - "Tests"
#   - "Core/Tests"
coverage:
  status:
    project:
      default:
        # basic
        target: 70%
        threshold: 10%
        # flags: 
        #   - unit
        # paths: 
        #   - "src"
       # advanced settings
        # branches: 
        #   - main
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
    patch:
      default:
        target: 60%
        threshold: 20%
